sudo: required
language: r
r_github_packages:
    - rstudio/rmarkdown
    - hadley/readr
    - hadley/ggplot2
    - hadley/stringr
    - mkoohafkan/kfigr
r_binary_packages:
    - magrittr
    - tidyr
    - reshape2
    - scales
    - geomorph
    - rjson
    - ipred
    - vegan
    - lubridate
    - directlabels
    - BAMMtools
    - knitcitations
script:
    - R CMD INSTALL .
    - Rscript -e 'rmarkdown::render("manuscript/manuscript.Rmd")'
