sudo: required
language: r
apt_packages:
    - texlive-xetex
    - texlive-humanities
    - latex-xcolor
    - pgf
r_github_packages:
    - rstudio/rmarkdown
    - hadley/readr
    - mkoohafkan/kfigr
before_script:
#    - curl -OL https://github.com/macroevolution/bamm/archive/v2.3.0.tar.gz
#    - tar -xvf v2.3.0.tar.gz
#    - cd bamm-2.3.0 && mkdir build && cd build && cmake .. && make -j && sudo make install
script:
    - R CMD INSTALL .
    - Rscript -e 'rmarkdown::render("manuscript/manuscript.Rmd")'
