sudo: required
language: r
r_github_packages:
    - rstudio/rmarkdown
    - hadley/readr
    - mkoohafkan/kfigr
r_binary_packages:
    - magrittr
    - tidyr
    - reshape2
    - scales
    - geomorph
    - rjson
    - ipred
    - vegan
    - lubridate
    - directlabels
    - BAMMtools
    - knitcitations
    - ggplot2
    - stringr
#before_script:
#    - curl -OL https://github.com/macroevolution/bamm/archive/v2.3.0.tar.gz
#    - tar -xvf v2.3.0.tar.gz
#    - cd bamm-2.3.0 && mkdir build && cd build && cmake .. && make -j && sudo make install
script:
    - R CMD INSTALL .
    - Rscript -e 'rmarkdown::render("manuscript/manuscript.Rmd")'
